schemaVersion: 2.2.0
metadata:
  name: coolstore-microservice-devx
attributes:
  che-theia.eclipse.org/sidecar-policy: mergeImage
components:
  - name: universal-developer-image
    container: 
      image: quay.io/openshiftlabs/mad-coolstore-devspaces:1.0
      memoryLimit: 6Gi
      mountSources: true
commands: []